// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddTumourboardHandlerFunc turns a function with the right signature into a add tumourboard handler
type AddTumourboardHandlerFunc func(AddTumourboardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddTumourboardHandlerFunc) Handle(params AddTumourboardParams) middleware.Responder {
	return fn(params)
}

// AddTumourboardHandler interface for that can handle valid add tumourboard params
type AddTumourboardHandler interface {
	Handle(AddTumourboardParams) middleware.Responder
}

// NewAddTumourboard creates a new http.Handler for the add tumourboard operation
func NewAddTumourboard(ctx *middleware.Context, handler AddTumourboardHandler) *AddTumourboard {
	return &AddTumourboard{Context: ctx, Handler: handler}
}

/*AddTumourboard swagger:route POST /tumourboard addTumourboard

adds a tumourboard

Adds a tumourboard to the system

*/
type AddTumourboard struct {
	Context *middleware.Context
	Handler AddTumourboardHandler
}

func (o *AddTumourboard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddTumourboardParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
