// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddDiagnosisCreatedCode is the HTTP code returned for type AddDiagnosisCreated
const AddDiagnosisCreatedCode int = 201

/*AddDiagnosisCreated item created

swagger:response addDiagnosisCreated
*/
type AddDiagnosisCreated struct {
}

// NewAddDiagnosisCreated creates AddDiagnosisCreated with default headers values
func NewAddDiagnosisCreated() *AddDiagnosisCreated {
	return &AddDiagnosisCreated{}
}

// WriteResponse to the client
func (o *AddDiagnosisCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddDiagnosisBadRequestCode is the HTTP code returned for type AddDiagnosisBadRequest
const AddDiagnosisBadRequestCode int = 400

/*AddDiagnosisBadRequest invalid input, object invalid

swagger:response addDiagnosisBadRequest
*/
type AddDiagnosisBadRequest struct {
}

// NewAddDiagnosisBadRequest creates AddDiagnosisBadRequest with default headers values
func NewAddDiagnosisBadRequest() *AddDiagnosisBadRequest {
	return &AddDiagnosisBadRequest{}
}

// WriteResponse to the client
func (o *AddDiagnosisBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddDiagnosisConflictCode is the HTTP code returned for type AddDiagnosisConflict
const AddDiagnosisConflictCode int = 409

/*AddDiagnosisConflict an existing item already exists

swagger:response addDiagnosisConflict
*/
type AddDiagnosisConflict struct {
}

// NewAddDiagnosisConflict creates AddDiagnosisConflict with default headers values
func NewAddDiagnosisConflict() *AddDiagnosisConflict {
	return &AddDiagnosisConflict{}
}

// WriteResponse to the client
func (o *AddDiagnosisConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
