// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddEnrollmentCreatedCode is the HTTP code returned for type AddEnrollmentCreated
const AddEnrollmentCreatedCode int = 201

/*AddEnrollmentCreated item created

swagger:response addEnrollmentCreated
*/
type AddEnrollmentCreated struct {
}

// NewAddEnrollmentCreated creates AddEnrollmentCreated with default headers values
func NewAddEnrollmentCreated() *AddEnrollmentCreated {
	return &AddEnrollmentCreated{}
}

// WriteResponse to the client
func (o *AddEnrollmentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddEnrollmentBadRequestCode is the HTTP code returned for type AddEnrollmentBadRequest
const AddEnrollmentBadRequestCode int = 400

/*AddEnrollmentBadRequest invalid input, object invalid

swagger:response addEnrollmentBadRequest
*/
type AddEnrollmentBadRequest struct {
}

// NewAddEnrollmentBadRequest creates AddEnrollmentBadRequest with default headers values
func NewAddEnrollmentBadRequest() *AddEnrollmentBadRequest {
	return &AddEnrollmentBadRequest{}
}

// WriteResponse to the client
func (o *AddEnrollmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddEnrollmentConflictCode is the HTTP code returned for type AddEnrollmentConflict
const AddEnrollmentConflictCode int = 409

/*AddEnrollmentConflict an existing item already exists

swagger:response addEnrollmentConflict
*/
type AddEnrollmentConflict struct {
}

// NewAddEnrollmentConflict creates AddEnrollmentConflict with default headers values
func NewAddEnrollmentConflict() *AddEnrollmentConflict {
	return &AddEnrollmentConflict{}
}

// WriteResponse to the client
func (o *AddEnrollmentConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
