// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddTreatmentCreatedCode is the HTTP code returned for type AddTreatmentCreated
const AddTreatmentCreatedCode int = 201

/*AddTreatmentCreated item created

swagger:response addTreatmentCreated
*/
type AddTreatmentCreated struct {
}

// NewAddTreatmentCreated creates AddTreatmentCreated with default headers values
func NewAddTreatmentCreated() *AddTreatmentCreated {
	return &AddTreatmentCreated{}
}

// WriteResponse to the client
func (o *AddTreatmentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddTreatmentBadRequestCode is the HTTP code returned for type AddTreatmentBadRequest
const AddTreatmentBadRequestCode int = 400

/*AddTreatmentBadRequest invalid input, object invalid

swagger:response addTreatmentBadRequest
*/
type AddTreatmentBadRequest struct {
}

// NewAddTreatmentBadRequest creates AddTreatmentBadRequest with default headers values
func NewAddTreatmentBadRequest() *AddTreatmentBadRequest {
	return &AddTreatmentBadRequest{}
}

// WriteResponse to the client
func (o *AddTreatmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddTreatmentConflictCode is the HTTP code returned for type AddTreatmentConflict
const AddTreatmentConflictCode int = 409

/*AddTreatmentConflict an existing item already exists

swagger:response addTreatmentConflict
*/
type AddTreatmentConflict struct {
}

// NewAddTreatmentConflict creates AddTreatmentConflict with default headers values
func NewAddTreatmentConflict() *AddTreatmentConflict {
	return &AddTreatmentConflict{}
}

// WriteResponse to the client
func (o *AddTreatmentConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
