// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddEnrollmentHandlerFunc turns a function with the right signature into a add enrollment handler
type AddEnrollmentHandlerFunc func(AddEnrollmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddEnrollmentHandlerFunc) Handle(params AddEnrollmentParams) middleware.Responder {
	return fn(params)
}

// AddEnrollmentHandler interface for that can handle valid add enrollment params
type AddEnrollmentHandler interface {
	Handle(AddEnrollmentParams) middleware.Responder
}

// NewAddEnrollment creates a new http.Handler for the add enrollment operation
func NewAddEnrollment(ctx *middleware.Context, handler AddEnrollmentHandler) *AddEnrollment {
	return &AddEnrollment{Context: ctx, Handler: handler}
}

/*AddEnrollment swagger:route POST /enrollment addEnrollment

adds an enrollment

Adds an enrollment to the system

*/
type AddEnrollment struct {
	Context *middleware.Context
	Handler AddEnrollmentHandler
}

func (o *AddEnrollment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddEnrollmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
