// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddConsentHandlerFunc turns a function with the right signature into a add consent handler
type AddConsentHandlerFunc func(AddConsentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddConsentHandlerFunc) Handle(params AddConsentParams) middleware.Responder {
	return fn(params)
}

// AddConsentHandler interface for that can handle valid add consent params
type AddConsentHandler interface {
	Handle(AddConsentParams) middleware.Responder
}

// NewAddConsent creates a new http.Handler for the add consent operation
func NewAddConsent(ctx *middleware.Context, handler AddConsentHandler) *AddConsent {
	return &AddConsent{Context: ctx, Handler: handler}
}

/*AddConsent swagger:route POST /consent addConsent

adds a consent

Adds a consent to the system

*/
type AddConsent struct {
	Context *middleware.Context
	Handler AddConsentHandler
}

func (o *AddConsent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddConsentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
