// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Biosample biosample
// swagger:model Biosample
type Biosample struct {

	// attributes
	Attributes Attributes `json:"attributes"`

	// collectionage
	// Required: true
	Collectionage *string `json:"collectionage"`

	// createddate
	Createddate string `json:"createddate,omitempty"`

	// description
	// Required: true
	Description *string `json:"description"`

	// disease
	Disease *Ontologyterm `json:"disease,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// individualid
	// Required: true
	Individualid *string `json:"individualid"`

	// name
	// Required: true
	Name *string `json:"name"`

	// updateddate
	Updateddate string `json:"updateddate,omitempty"`
}

// Validate validates this biosample
func (m *Biosample) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollectionage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDisease(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIndividualid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Biosample) validateCollectionage(formats strfmt.Registry) error {

	if err := validate.Required("collectionage", "body", m.Collectionage); err != nil {
		return err
	}

	return nil
}

func (m *Biosample) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *Biosample) validateDisease(formats strfmt.Registry) error {

	if swag.IsZero(m.Disease) { // not required
		return nil
	}

	if m.Disease != nil {

		if err := m.Disease.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("disease")
			}
			return err
		}
	}

	return nil
}

func (m *Biosample) validateIndividualid(formats strfmt.Registry) error {

	if err := validate.Required("individualid", "body", m.Individualid); err != nil {
		return err
	}

	return nil
}

func (m *Biosample) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Biosample) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Biosample) UnmarshalBinary(b []byte) error {
	var res Biosample
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
