// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Ontologyterm ontologyterm
// swagger:model Ontologyterm
type Ontologyterm struct {

	// ontology
	Ontology string `json:"ontology,omitempty"`

	// term
	// Required: true
	Term *string `json:"term"`

	// termid
	// Required: true
	Termid *string `json:"termid"`
}

// Validate validates this ontologyterm
func (m *Ontologyterm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTerm(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTermid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ontologyterm) validateTerm(formats strfmt.Registry) error {

	if err := validate.Required("term", "body", m.Term); err != nil {
		return err
	}

	return nil
}

func (m *Ontologyterm) validateTermid(formats strfmt.Registry) error {

	if err := validate.Required("termid", "body", m.Termid); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Ontologyterm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ontologyterm) UnmarshalBinary(b []byte) error {
	var res Ontologyterm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
