// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Patient patient
// swagger:model Patient
type Patient struct {

	// autopsy tissue for research
	AutopsyTissueForResearch *string `json:"autopsy_tissue_for_research,omitempty" db:"autopsy_tissue_for_research"`

	// cause of death
	CauseOfDeath *string `json:"cause_of_death,omitempty" db:"cause_of_death"`

	// date of birth
	DateOfBirth *string `json:"date_of_birth,omitempty" db:"date_of_birth"`

	// date of death
	DateOfDeath *string `json:"date_of_death,omitempty" db:"date_of_death"`

	// details of predisposition syndrome
	DetailsOfPredispositionSyndrome *string `json:"details_of_predisposition_syndrome,omitempty" db:"details_of_predisposition_syndrome"`

	// ethnicity
	Ethnicity *string `json:"ethnicity,omitempty" db:"ethnicity"`

	// family history and risk factors
	FamilyHistoryAndRiskFactors *string `json:"family_history_and_risk_factors,omitempty" db:"family_history_and_risk_factors"`

	// family history of predisposition syndrome
	FamilyHistoryOfPredispositionSyndrome *string `json:"family_history_of_predisposition_syndrome,omitempty" db:"family_history_of_predisposition_syndrome"`

	// gender
	Gender *string `json:"gender,omitempty" db:"gender"`

	// genetic cancer syndrome
	GeneticCancerSyndrome *string `json:"genetic_cancer_syndrome,omitempty" db:"genetic_cancer_syndrome"`

	// occupational or environmental exposure
	OccupationalOrEnvironmentalExposure *string `json:"occupational_or_environmental_exposure,omitempty" db:"occupational_or_environmental_exposure"`

	// other genetic condition or significant comorbidity
	OtherGeneticConditionOrSignificantComorbidity *string `json:"other_genetic_condition_or_significant_comorbidity,omitempty" db:"other_genetic_condition_or_significant_comorbidity"`

	// other ids
	OtherIds *string `json:"other_ids,omitempty" db:"other_ids"`

	// patient id
	PatientID *string `json:"patient_id,omitempty" db:"patient_id"`

	// sample id
	SampleID *string `json:"sample_id,omitempty" db:"sample_id"`

	// prior malignancy
	PriorMalignancy *string `json:"prior_malignancy,omitempty" db:"prior_malignancy"`

	// province of residence
	ProvinceOfResidence *string `json:"province_of_residence,omitempty" db:"province_of_residence"`

	// race
	Race *string `json:"race,omitempty" db:"race"`
}

// Validate validates this patient
func (m *Patient) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Patient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Patient) UnmarshalBinary(b []byte) error {
	var res Patient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
