package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// Record record
// swagger:model Record
type Record struct {

	// complication
	Complication

	// consent
	Consent

	// diagnosis
	Diagnosis

	// enrollment
	Enrollment

	// outcome
	Outcome

	// patient
	Patient

	// sample
	Sample

	// treatment
	Treatment

	// tumourboard
	Tumourboard
}

// MarshalBinary interface implementation
func (m *Record) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Record) UnmarshalBinary(b []byte) error {
	var res Record
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
